### PR TITLE
Add javadocs for delete lesson related methods in UniqueLessonList

### PR DESCRIPTION
**Pull request by ethantyh692**

### CODE REVIEW

**Comment by NorbertLoh** [comment]
Should we caps the If for all return and throws in javadocs?

**Comment by Chronoxy** [comment]
> Should we caps the If for all return and throws in javadocs?

for which line would that be?

**Comment by ethantyh692** [comment]
> Should we caps the If for all return and throws in javadocs?

need for the return?

**Comment by NorbertLoh** [comment]
> > Should we caps the If for all return and throws in javadocs?
> 
> need for the return?

Maybe just throw 👍

**Comment by ethantyh692** [comment]
@NorbertLoh @Chronoxy Fixed

**Pull request merged**
